package com.wildlifetracker.models;

import jakarta.persistence.*;
import java.time.LocalDate;

// Sighting model - represents a wildlife sighting reported by a user
// maps to the "sightings" table in the database
// similar setup to Species, each field = a column
@Entity
@Table(name = "sightings")
public class Sighting {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // auto-generated by the database

    // the name of the species that was spotted (typed in by the user)
    // we use a String here rather than a foreign key to Species to keep it simple
    private String speciesName;

    // where the sighting took place e.g. "Hyde Park London"
    private String location;

    // the date the sighting happend
    // LocalDate is just a date (no time) which is fine for sightings
    // spring/jackson handles convertion to and from ISO format strings (e.g. "2024-11-12")
    private LocalDate date;

    // any extra details the user wants to add about what they saw
    private String description;

    // who submitted this sighting
    private String reportedBy;

    // optionally the user can say if the animal looked healthy or not
    private String healthStatus;

    // empty constructor needed by hibernate
    public Sighting() {}

    // full constructor used in DatabaseInit to create sample sightings
    public Sighting(Long id, String speciesName, String location, LocalDate date,
                    String description, String reportedBy, String healthStatus) {
        this.id = id;
        this.speciesName = speciesName;
        this.location = location;
        this.date = date;
        this.description = description;
        this.reportedBy = reportedBy;
        this.healthStatus = healthStatus;
    }

    // getters and setters - required for JSON serialisation and for the update method in the service
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getSpeciesName() { return speciesName; }
    public void setSpeciesName(String speciesName) { this.speciesName = speciesName; }

    public String getLocation() { return location; }
    public void setLocation(String location) { this.location = location; }

    public LocalDate getDate() { return date; }
    public void setDate(LocalDate date) { this.date = date; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public String getReportedBy() { return reportedBy; }
    public void setReportedBy(String reportedBy) { this.reportedBy = reportedBy; }

    public String getHealthStatus() { return healthStatus; }
    public void setHealthStatus(String healthStatus) { this.healthStatus = healthStatus; }
}
